<a href="https://colab.research.google.com/github/ikah-uni/MMA3001-Concrete-Strength-Prediction/blob/main/MMA3001_Concrete_Strength.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:

import os

print(os.listdir("/content"))

['.config', '.ipynb_checkpoints', 'Concrete_Data.xls', 'sample_data']

Use Pandas to read the excel sheet

In [4]:

import pandas as pd

# Install support for older Excel (.xls) files
%pip -q install xlrd

# Read the Excel file and store it in a DataFrame
df = pd.read_excel("/content/Concrete_Data.xls")

# Display the first five rows
display(df.head())

# Display the number of rows and columns
print("Dataset shape:", df.shape)

,Cement (component 1)(kg in a m^3 mixture),Blast Furnace Slag (component 2)(kg in a m^3 mixture),Fly Ash (component 3)(kg in a m^3 mixture),Water (component 4)(kg in a m^3 mixture),Superplasticizer (component 5)(kg in a m^3 mixture),Coarse Aggregate (component 6)(kg in a m^3 mixture),Fine Aggregate (component 7)(kg in a m^3 mixture),Age (day),"Concrete compressive strength(MPa, megapascals)"
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

Dataset shape: (1030, 9)

Change the column headings to improve readability

In [5]:

# Rename columns for easier use
df.columns = [
    "Cement",
    "Blast_Furnace_Slag",
    "Fly_Ash",
    "Water",
    "Superplasticizer",
    "Coarse_Aggregate",
    "Fine_Aggregate",
    "Age",
    "Strength"
]

# Display the first five rows
display(df.head())

,Cement,Blast_Furnace_Slag,Fly_Ash,Water,Superplasticizer,Coarse_Aggregate,Fine_Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.986111
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.887366
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.269535
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.052780
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.296075

Now we are going to filter out the unusable data

In [6]:

# Check dataset dimensions
print("Dataset shape:", df.shape)

# Check for missing values
print("\nMissing values:")
print(df.isnull().sum())

# Generate descriptive statistics
print("\nStatistical Summary:")
display(df.describe())

# Check duplicate observations
print("\nDuplicate rows:", df.duplicated().sum())

Dataset shape: (1030, 9)

Missing values:
Cement                0
Blast_Furnace_Slag    0
Fly_Ash               0
Water                 0
Superplasticizer      0
Coarse_Aggregate      0
Fine_Aggregate        0
Age                   0
Strength              0
dtype: int64

Statistical Summary:

,Cement,Blast_Furnace_Slag,Fly_Ash,Water,Superplasticizer,Coarse_Aggregate,Fine_Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.165631,73.895485,54.187136,181.566359,6.203112,972.918592,773.578883,45.662136,35.817836
std,104.507142,86.279104,63.996469,21.355567,5.973492,77.753818,80.175427,63.169912,16.705679
min,102.000000,0.000000,0.000000,121.750000,0.000000,801.000000,594.000000,1.000000,2.331808
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.707115
50%,272.900000,22.000000,0.000000,185.000000,6.350000,968.000000,779.510000,28.000000,34.442774
75%,350.000000,142.950000,118.270000,192.000000,10.160000,1029.400000,824.000000,56.000000,46.136287
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.599225

Duplicate rows: 25

Removing duplicate rows

In [7]:

# Record original dataset size
original_rows = len(df)

# Remove exact duplicate observations
df = df.drop_duplicates().reset_index(drop=True)

# Calculate number of removed rows
removed_rows = original_rows - len(df)

print("Original observations:", original_rows)
print("Duplicates removed:", removed_rows)
print("Remaining observations:", len(df))

Original observations: 1030
Duplicates removed: 25
Remaining observations: 1005